name: FormAPI
main: NurAzliYT\FormAPI\FormAPI
version: 1.0.0
api: 5.0.0
author: NurAzliYT
description: "For Developer Tools, For Create "

commands:
  fapi:
      description: "FormAPI Commands"
      permission: fapi.command

permissions:
  fapi.command:
      default: op
commands:
  formapi:
      description: "FormAPI Commands"
      permission: formapi.command

permissions:
  Form.command:
      default: op
      
